In [2]:
import pandas as pd
import numpy as np

order_history = pd.DataFrame({
  "order_id": [1, 2, 3, 4, 5, 6, 7, 8],
  "cust_no": ["C1", "C2", "C3", "C5", "C6", "C7", "C8", "C10"],
  "order_amount": [100, 200, 250, 150, 300, 350, 100, 150]
})

customer_base = pd.DataFrame({
  "cust_id": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"],
  "city": ["Bandung", "Jakarta", "Tangerang", "Tangerang", "Jakarta", "Jakarta", "Jakarta", "Bandung", "Tangerang", "Jakarta"],
})

In [2]:
order_history

   order_id cust_no  order_amount
0         1      C1           100
1         2      C2           200
2         3      C3           250
3         4      C5           150
4         5      C6           300
5         6      C7           350
6         7      C8           100
7         8     C10           150

In [3]:
customer_base

  cust_id       city
0      C1    Bandung
1      C2    Jakarta
2      C3  Tangerang
3      C4  Tangerang
4      C5    Jakarta
5      C6    Jakarta
6      C7    Jakarta
7      C8    Bandung
8      C9  Tangerang
9     C10    Jakarta

In [5]:
df_merge = order_history.merge(customer_base, how="left", left_on="cust_no", right_on="cust_id")

In [6]:
df_merge

   order_id cust_no  order_amount cust_id       city
0         1      C1           100      C1    Bandung
1         2      C2           200      C2    Jakarta
2         3      C3           250      C3  Tangerang
3         4      C5           150      C5    Jakarta
4         5      C6           300      C6    Jakarta
5         6      C7           350      C7    Jakarta
6         7      C8           100      C8    Bandung
7         8     C10           150     C10    Jakarta

In [23]:
result = pd.DataFrame(df_merge.groupby(["city"])["order_amount"].sum())

In [24]:
result

           order_amount
city
Bandung             200
Jakarta            1150
Tangerang           250

In [25]:
result.sort_values("order_amount", ascending=False)

           order_amount
city
Jakarta            1150
Tangerang           250
Bandung             200

In [26]:
# cara ka fani

In [10]:
order_history

   order_id cust_no  order_amount
0         1      C1           100
1         2      C2           200
2         3      C3           250
3         4      C5           150
4         5      C6           300
5         6      C7           350
6         7      C8           100
7         8     C10           150

In [11]:
customer_base

  cust_id       city
0      C1    Bandung
1      C2    Jakarta
2      C3  Tangerang
3      C4  Tangerang
4      C5    Jakarta
5      C6    Jakarta
6      C7    Jakarta
7      C8    Bandung
8      C9  Tangerang
9     C10    Jakarta

In [12]:
order_history.merge(customer_base, how="inner", left_on="cust_no", right_on="cust_id")

   order_id cust_no  order_amount cust_id       city
0         1      C1           100      C1    Bandung
1         2      C2           200      C2    Jakarta
2         3      C3           250      C3  Tangerang
3         4      C5           150      C5    Jakarta
4         5      C6           300      C6    Jakarta
5         6      C7           350      C7    Jakarta
6         7      C8           100      C8    Bandung
7         8     C10           150     C10    Jakarta

In [14]:
df_new_data =order_history.merge(customer_base, how="inner", left_on="cust_no", right_on="cust_id").drop(columns=["cust_id"])

In [28]:
df_new_data

   order_id cust_no  order_amount       city
0         1      C1           100    Bandung
1         2      C2           200    Jakarta
2         3      C3           250  Tangerang
3         4      C5           150    Jakarta
4         5      C6           300    Jakarta
5         6      C7           350    Jakarta
6         7      C8           100    Bandung
7         8     C10           150    Jakarta

In [29]:
df_new_data.groupby(["city"]).agg({"order_amount": "sum"})

           order_amount
city
Bandung             200
Jakarta            1150
Tangerang           250

In [30]:
# harus pake reset index agar city dengan order_amount itu berada di level yang sama
data_sum_order = df_new_data.groupby(["city"]).agg({"order_amount": "sum"}).reset_index()

In [31]:
data_sum_order

        city  order_amount
0    Bandung           200
1    Jakarta          1150
2  Tangerang           250

In [32]:
data_sum_order.columns = ["city", "total_order_amount"]

In [33]:
data_sum_order

        city  total_order_amount
0    Bandung                 200
1    Jakarta                1150
2  Tangerang                 250

In [36]:
data_sum_order.sort_values("total_order_amount", ascending = False).reset_index(drop = True)

        city  total_order_amount
0    Jakarta                1150
1  Tangerang                 250
2    Bandung                 200