In [9]:
import pandas as pd
import numpy as np

dict_data = {
  "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
  "age": [25, 30, 35, 40, 45],
  "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
}

In [10]:
df = pd.DataFrame(dict_data)

In [11]:
df

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix

In [13]:
df.to_csv("data.csv", index=False)

In [14]:
df.to_excel("data.xlsx", index=False)

In [18]:
pd.read_csv("data.csv")

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix